name: Cont2Sas
channels:
  - conda-forge
dependencies:
  - python=3.12.1
  - h5py=3.14.0
  - imageio=2.37.0
  - matplotlib=3.10.3
  - netCDF4=1.7.2
  - numpy=2.3.1
  - openmpi=4.0.3
  - PyMuPDF==1.26.1
  - scipy=1.16.0
  - pip=25.1  # pip is included for security