name: sas
channels:
  - defaults
dependencies:
  - python=3.12.1
  - pip=25.1  # Make sure pip is included
  - pip:
      - fitz
      - h5py
      - imageio
      - matplotlib
      - netCDF4
      - numpy
      - scipy